Sprint 3
dannysonn/middle.messenger.praktikum.yandex pull request #6
Opened 2022-11-28 17:43 UTC by dannysonn

2022-11-28 18:03 UTC, podlovchenko requested changes
Добрый вечер
1. На нетлифай при обновлении страницы page not found, необходимо настроить redirects в netlify.toml https://docs.netlify.com/routing/redirects/
2. Не работает валидация данных на странице регистрации
3. Нет редиректа на страницу чатов, если пользователь уже в системе
4. Использование any не очень хорошая практика, теряются преимущества typescript
5.  Было бы отлично почистить проект от закомментированного кода
6. При обновлении страницы локально `Cannot GET /registration`
По заданию
<img width="823" alt="Снимок экрана 2022-11-28 в 21 01 40" src="https://user-images.githubusercontent.com/22602747/204348582-b52c0dfc-71de-4a4f-bc26-ab0c208294f8.png">
7. Поехала верстка в списке чатов
<img width="329" alt="Снимок экрана 2022-11-28 в 21 02 06" src="https://user-images.githubusercontent.com/22602747/204348628-f43ddcbe-5d06-41e3-b763-0828b5560fc5.png">

2022-11-28 18:03 UTC, podlovchenko commented on package.json
> +    "@babel/core": "^7.20.2",
Лучше задавать фиксированные версии зависимостям. Если однажды решишь, удалить package-lock.json файл и попытаться повторно установить зависимости с помощью команды npm install, npm установит последние версии зависимостей, что может привести к ошибкам

2022-11-28 18:03 UTC, podlovchenko commented on src/api/AuthApi.ts
> +  public signIn(data: any) {
Стоит описать типы для data

2022-11-28 18:03 UTC, podlovchenko commented on src/pages/Login/index.ts
> +//
Закомментированный код лучше не оставлять в проекте

2022-11-28 20:56 UTC, dannysonn commented
Добрый вечер, отрефакторил

2022-11-28 20:56 UTC, dannysonn commented on src/pages/Login/index.ts
> +//
Вроде бы убрал везде комменты

2022-11-29 09:35 UTC, podlovchenko commented
Привет, локально при обновлении страницы `Cannot GET /chats`
Необходимо добавить в server.js
```
app.get('*', (req, res) => {
    res.sendFile(path.join(__dirname, '../dist/index.html'))
})
```

2022-11-29 09:36 UTC, dannysonn commented
@podlovchenko привет, у меня локально нет проблем с перезагрузкой страницы почему-то. На mac os и windows корректно всё, при обновлении тоже.

2022-11-29 09:43 UTC, dannysonn commented
Понял, собирался в dev

2022-11-29 13:15 UTC, podlovchenko commented
Работу принимаю)

2022-12-05 18:05 UTC, merged